steps:
# Install dependencies and build your application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

# Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud' 
    args: ['app', 'deploy', 'app.yaml', '--version', '${_VERSION}', '--project', '${_PROJECT_ID}'] 

# Optionally, you can specify the build timeout and other settings.
substitutions:
  _PROJECT_ID: reacthomeloan-388609
  _VERSION: 1-0-0
# timeout: 1200s
# queueTtl:  3600s
options:
  logging : CLOUD_LOGGING_ONLY
